Laboratoria/gym

exercises/count-characters/README.md
exercises/count-positives-sum-negatives/README.md

Seba van los ejercicios
-  count-characters
-  count-positives-sum-negatives
el ejercicio "css-web_maker_logo" ya tenía formato

Front Matter para ejercicios que empiezan con C

---

cohorts/README.md

4. una carpeta solutions con un archivo para cada solucion propuesta al reto

links a repositorio gimnasio cohort SCL020

---

cohorts/README.md

agregando los links de los repos de GYM de SAP007 y el actual cohort SAP008

add cohort SAP007 y SAP008

---

cohorts/README.md

- Organize cohort README
- Add BOG005 cohort

Add BOG005 cohort

---

exercises/README.md
exercises/kinemartophobia/README.md
exercises/kinemartophobia/README.pt-BR.md
sessions/session-03.md

fuente:
https://www.simplilearn.com/tutorials/programming-tutorial/logical-reasoning-questions-and-answers
Actualmente tenemos estudiantes que les esta siendo retador JS en bootcamp y este ejercicio esta pensado para arrancar la sesión razonando un poco la forma de resolver.

Add exercise no code

---

sessions/session-01.md

@icarito @ssinuco @merunga  in this PR add the kahoot to session1 (kickoff)

add kahoot to session one

---

sessions/session-05.md

Se corrige link del kahoot para la sesion 5

Fix session 5 kahoot link

---

sessions/session-08.md

Se corrige link del kahoot para la sesion 8

Fix session 8 kahoot link

---

cohorts/MEX012/session-05/README.md
exercises/README.md
exercises/list-filtering/README.md
exercises/list-filtering/README.pt-BR.md
sessions/session-05.md

@icarito @merunga, in the cohort CDMX013 we detected a students that feel the project data lovers some hard in the part of filter, so the coaches thing about add a new exercise with filter and the students approach to the filter with this exercise beginner.
Share my solutions (declarative and imperative) 
https://github.com/Laboratoria/gym-solutions/pull/11

Add beginner exercise filter

---

sessions/session-01.md

update con ejercicios code

---

exercises/count-clumps/README.md
exercises/count-clumps/README.pt-BR.md
sessions/session-05.md

Nuevo ejercicio de arreglos nivel avanzado

countClumps exercise

---

exercises/max-span/README.md
exercises/max-span/README.pt-BR.md
sessions/session-06.md

Nuevo ejercicio de arreglos avanzado

maxSpan exercise

---

exercises/number-of-islands/README.md
exercises/number-of-islands/README.pt-BR.md
sessions/session-12.md

A advanced exercise with recursion

Number of Islands exercise

---

exercises/blackjack/README.md
exercises/blackjack/README.pt-BR.md
sessions/session-03.md

Ejercicio de dificultad intermediate para ser usado de la sesion 2 a la 5, se resuleve con condicionales, idea para las estudiantes que estan en el proyecto card validation o cipher.

blackjack exercise

---

exercises/count-x-recursion/README.md
exercises/count-x-recursion/README.pt-BR.md
sessions/session-14.md

Ejercicio de recursion pensado para las estudiantes que estan en MD Links

countX exercise

---

exercises/parity-outlier/README.md
exercises/parity-outlier/README.pt-BR.md
sessions/session-09.md

4. una carpeta solutions con un archivo para cada solucion propuesta al reto

New beginner excercise for session 09.

---

exercises/make-chocolate/README.md
exercises/make-chocolate/README.pt-bR.md
sessions/session-04.md

Ejercicio de dificultad intermediate para ser usado en las sesiones 2 a 5, se resuleve con condicionales, ideal para estudiantes que estan en los proyectos card validation o cipher

Make chocolate

---

sessions/session-04.md

Es solo la creación de la sesión 4

añadida sesión 4

---

sessions/session-04.md
sessions/session-05.md

Dev004 session 5

---

exercises/str-count/README.md
exercises/str-count/README.pt-BR.md
sessions/session-13.md

Nuevo ejercicio para practicar strings en la sesion 13

intermediate exercise str-count to practice strings

---

exercises/array-6/README.md
exercises/end-x/README.md
exercises/max-mirror/README.md
exercises/square-up/README.md
exercises/str-count/README.md
exercises/sum-numbers/README.md
exercises/xy-balance/README.md
sessions/session-05.md
sessions/session-10.md
sessions/session-17.md

add session 17

---

sessions/session-18.md

add retrospective session

---

exercises/remove-string-spaces/README.md
exercises/remove-string-spaces/README.pt-BR.md

Sesion 3 remove string spaces

---

exercises/id-card/README.md
exercises/id-card/README.pt-BR.md

La idea es simular un escenario real  cuando un desarrollador tiene que implementar funcionalidades a un código compartido. En este caso se le comparte una plantilla que tiene todos los elementos en HTML y CSS pero nada de JS.
El ejercicio trata de generar una identificación que tenga:
- Nombres: Que se obtendrán desde un input en el formulario
- Firma: El usuario puede dibujar su firma y en caso de equivocarse la puede borrar.
- Foto: Imagen que se obtiene desde una cámara web.
A ideia é simular um cenário real quando um desenvolvedor precisa implementar funcionalidades em um código compartilhado. Nesse caso, um modelo é compartilhado com você com todos os elementos em HTML e CSS, mas sem JS.
O exercício tenta gerar um ID que tenha:
- Nomes: Que serão obtidos a partir de uma entrada no …

[AI-Exercise] ID Card

---

exercises/square-up/README.md
exercises/square-up/README.pt-BR.md
sessions/session-14.md

Nuevo ejercicio para practicar arreglos en la sesion 14

advanced exercise squareUp to practice arrays

---

exercises/array-6/README.md
exercises/array-6/README.pt-BR.md
sessions/session-15.md

Nuevo ejercicio para practica recursion en la sesion 15

exercise array6 to practice recursion

---

exercises/xy-balance/README.md
exercises/xy-balance/README.pt-BR.md
sessions/session-15.md

Nuevo ejercicio para practicar strings en la sesion 15

xy balance exercise to practice strings

---

exercises/first-last-6/README.md
exercises/first-last-6/README.pt-BR.md
exercises/hello-name/README.md
exercises/hello-name/README.pt-BR.md
exercises/int-max/README.pt-BR.md

Se agregan pistas para resolver los ejercicios de la sesion 2; issue #300

Add tips for session 2 exercises

---

exercises/max-mirror/README.md
exercises/max-mirror/README.pt-BR.md
sessions/session-13.md

Nuevo ejercicio para practicar arreglos en la sesion 13

max mirror exercise to practice arrays

---

docs/interviews/first-tech-mock-interview/README-Interviewer.md
exercises/can-balance/README.md
exercises/findpairforsum/README.md
exercises/findpairforsum/README.pt-BR.md

4. una carpeta solutions con un archivo para cada solucion propuesta al reto

exercise findPairForSum

---

exercises/ia-transpose-matrix/README.md
exercises/ia-transpose-matrix/README.pt-BR.md

This exercise is thinking for getting start with de session and warm up with IA.
- This is the [solution](https://github.com/Laboratoria/gym-solutions/pull/30)

feat: :sparkles: Add exercise beginner of IA with matrix.

---

sessions/session-ia.md

@icarito @envm92 @MarciaMillanao This [PR](https://github.com/Laboratoria/gym/pull/360) have the exercise with IA, but I don't know the correct timing to run this session.
Maybe we will talk about this.

feat: :sparkles: add new session with IA

---

sessions/session-05.md
sessions/session-13.md
sessions/session-14.md
sessions/session-15.md

@icarito añadidos /README a varios ejercicios

Fixsession05

---

exercises/at-first/README.pt-BR.md
exercises/cat-dog/README.md
exercises/cat-dog/README.pt-BR.md
exercises/count-hi/README.pt-BR.md
exercises/g-happy/README.pt-BR.md
exercises/see-color/README.md
exercises/see-color/README.pt-BR.md

Hola! 
He notado y corrigido alguns pequeños detalles en la traduccion de los ejercicios de la session 17 en pt-BR.
También he corrigido en dos archivos en español, `see-colors` y `cat-dog`.

small fixes in s17 exercises

---

sessions/docs-kahoot/session-13.md

**[ES]**
Se sugiere utilizar el siguiente formato para dejar constancia de la documentación relacionada con el Kahoot de cada sesión.
El formato propuesto incluye:
- Enlace al Kahoot.
- El temario.
Tema: Se proporciona una descripción del tema, se ofrece un ejemplo y se adjunta un enlace a la documentación relacionada.
----
**[PR]**
Recomenda-se utilizar o seguinte padrão para registrar a documentação relacionada ao Kahoot de cada sessão.
O padrão sugerido compreende:
- Link para Kahoot.
- A pauta da reunião.
Assunto: É fornecida uma descrição do assunto, com um exemplo e um anexo contendo o link para a documentação relacionada.
---

Propuesta documentación Kahoot
